name: Java CI


on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # required by wagoid/commitlint-github-action to validate range of commits instead of just the latest one
      - uses: wagoid/commitlint-github-action@v4
        if: matrix.os == 'ubuntu-latest'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: rm -rf /tmp/*
        continue-on-error: true
      - name: Build with Maven (not Windows)
        env:
          AWS_REGION: us-west-2
        run: mvn -ntp -U clean verify
        if: matrix.os != 'windows-latest'
      - name: Build with Maven (Windows)
        env:
          AWS_REGION: us-west-2
        run: mvn -ntp -U clean verify
        shell: cmd
        if: matrix.os == 'windows-latest'
      - name: Upload Failed Test Report
        uses: actions/upload-artifact@v1.0.0
        if: failure()
        with:
          name: Failed Test Report
          path: target/surefire-reports
      - name: Upload Coverage
        uses: actions/upload-artifact@v1.0.0
        if: matrix.os == 'ubuntu-latest'
        with:
          name: Coverage Report ${{ matrix.os }}
          path: target/jacoco-report
      - name: Upload unit test coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: target/jacoco-report
          files: jacoco.xml
          flags: unit
      - name: Upload integration test coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: target/jacoco-report/jacoco-it
          files: jacoco.xml
          flags: integration
      - name: Convert Jacoco unit test report to Cobertura
        run: python3 .github/scripts/cover2cover.py target/jacoco-report/jacoco.xml src/main/java > target/jacoco-report/cobertura.xml
      - name: Convert Jacoco integ test report to Cobertura
        run: python3 .github/scripts/cover2cover.py target/jacoco-report/jacoco-it/jacoco.xml src/main/java > target/jacoco-report/cobertura-it.xml
